sidebar:
  menu:
    post: '[文章](/)'
    wiki: '[关于](/about/)'
  widgets:
    index: [ghuser, recent, timeline] # for home/wiki/categories/tags/archives/404 pages
    page: [toc] # for pages using 'layout:page'
    post: [toc, ghrepo, ghissues] # for pages using 'layout:post'
    about: [timeline, ghrepo, ghuser]
    recent:
      rss: /atom.xml # npm i hexo-generator-feed

article:
  share: [wechat, weibo, email, link]
  related_posts:
    enable: true
    auto_cover: true

search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: true # 是否搜索代码块（需要content: true)

footer:
  social:
    github:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/08a41b181ce68.svg"/>'
      url: https://github.com/lifeafter619
    music:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/3845874.svg"/>'
      url: https://music.163.com/#/user/home?id=1995068708
    comments:
      icon: '<img src="https://fastly.jsdelivr.net/gh/cdn-x/placeholder@1.0.3/social/942ebbf1a4b91.svg"/>'
      url: /about/#comments
    links:
      icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.4/social/8411ed322ced6.svg"/>'
      url: https://66619.eu.org
    email:
      icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.4/social/a1b00e20f425d.svg"/>'
      url: mailto:mail@66619.eu.org
  sitemap:
    '博客':
      - '[近期](/)'
      - '[归档](/archives/)'
    '社交':
      - '[主站](https://66619.eu.org)'
      - '[友链](/friends/)'
      - '[留言板](/about/#comments)'
    '更多':
      - '[关于](/about/)'
      - '[GitHub](https://github.com/lifeafter619)'
      - '[GitLab](https://gitlab.com/lifeafter619)'
      - '[Gitee](https://gitee.com/ethereal619)'
  source: '[GitHub](https://github.com/lifeafter619/lifeafter619.github.io/)'
  content: | # 支持 Markdown 格式
    本站由 [@619](/) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。

comments:
  service: waline
  waline:
    js: https://unpkg.com/@waline/client@v2/dist/waline.js
    css: https://unpkg.com/@waline/client@v2/dist/waline.css
    # Waline server address url, you should set this to your own link
    serverURL: https://66619.deta.dev # waline 地址
    # If false, comment count will only be displayed in post page, not in home page
    commentCount: true
    # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
    pageview: false

    # Custom locales
    locale:
      placeholder: 来叭叭，信息都不留也行哈~

    # Custom emoji
    emoji: 
        - https://gcore.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs
    #   - https://unpkg.com/@waline/emojis@1.1.0/weibo
    #   - https://unpkg.com/@waline/emojis@1.1.0/alus
    #   - https://unpkg.com/@waline/emojis@1.1.0/bilibili
    #   - https://unpkg.com/@waline/emojis@1.1.0/qq
    #   - https://unpkg.com/@waline/emojis@1.1.0/tieba
    #   - https://unpkg.com/@waline/emojis@1.1.0/tw-emoji
    #   - https://unpkg.com/@waline/emojis@1.1.0/bmoji

    # Comment infomation, valid meta are nick, mail and link
    # meta:
    #   - 昵称
    #   - 邮箱
    #   - 链接

    # Set required meta field, e.g.: [nick] | [nick, mail]
    # requiredMeta:
    #   - nick

    # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    lang: zh-CN

    wordLimit: 0 # 字数限制，0为不限制字数

    # Whether enable login, can choose from 'enable', 'disable' and 'force'
    # login: enable

    # comment per page
    pageSize: 5 # 每页显示评论数

style:
  color:
    common:
      theme: '#1BCDFC' # 主题色
      accent: '#ff5722' # 强调色
      link: '#2196f3' # 超链接颜色
      button: '#1BCDFC' # 按钮颜色
      hover: '#ff5722' # 按钮高亮颜色
    light:
      background: '#f8f8f8' # 浅色背景颜色
      block: '#f2f2f2' # 块背景颜色
      card: white # 卡片背景颜色
      title: '#000' # 标题文本颜色
      text: '#333' # 正文文本颜色
      code: '#111' # 行内代码颜色
    dark:
      background: '#313438' # 深色背景颜色
      background-mobile: black # 移动端深色背景（OLED调成纯黑可以省电）
      block: '#2B2F33' # 块背景颜色
      card: '#464D57' # 卡片背景颜色
      title: '#fff' # 标题文本颜色
      text: '#eee' # 正文文本颜色
      code: '#ff7043' # 行内代码颜色
  codeblock:
    scrollbar: 0px
  font-size: 16px
  font-family:
    logo: 'system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: 'system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'

######## Tag Plugins ########
tag_plugins:
  # {% image %}
  image:
    fancybox: true